name: Deploy Azure Infrastructure with Bicep

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Debug file structure
      run: ls -R

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep Template
      run: |
        az deployment group create \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --name deploy-bicep \
          --template-file ./Infrastracture/main.bicep \
          --parameters openAiApiKey=${{ secrets.OPEN_AI_API_KEY }} \
          --parameters githubClientId=${{ secrets.GH_CLIENT_ID }} \
          --parameters githubClienSecret=${{ secrets.GH_CLIENT_SECRET }}
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
