name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Python and create a virtual environment
    - name: Set up Python and Install Dependencies
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r WebApp/requirements.txt

    # Step 3: Zip the application, excluding virtual environment
    - name: Prepare Deployment Package
      run: |
        cd WebApp
        zip -r ../WebApp.zip . -x "venv/**" "*.pyc" "__pycache__/**"

    # Step 4: Login to Azure
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 5: Deploy to Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: webapp-z25l7o43hwqe6  # Replace with your app name
        package: WebApp.zip
        publish-profile: ${{ secrets.APP_SERVICE_PUBLISH_PROFILE }}
